version: '3.8'

services:
    postgres:
        container_name: postgres_users
        image: postgres:15
        environment:
            POSTGRES_DB: users_db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - 5432:5432
